services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bank_rest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1987
    ports:
      - "5432:5432"
    volumes:
      - bank_db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_rest
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1987
    depends_on:
      - db

volumes:
  bank_db_data:
